# Mandatory settings

name: Helium
paginate: 16
url: https://helium.jxhe.xyz # add your site url (format: https://example.com/)
blog_theme: light # Or use dark

# Optional settings

about_enabled: false # Change to true if you wish to show an icon in the navigation that redirects to the about page
discus_identifier: jhelium # Add your Disqus identifier
ga_analytics: UA-102195522-1 # Add your GA Tracking Id
local_fonts: false # Change to true if you wish to use local fonts
rss_enabled: true # Change to false if not
social:
  instagram: jason_he233/ # Add your Instagram handle
  github: JasonBourbaki # Add your GitHub handle
  linkedin: jiaxin-h-025498123/ # Add your LinkedIn handle
  twitter: # Add your Twitter handle
  email: jasonhe233@hotmail.com # Add your Email address

# Random redirect settings
random_redirect:
  posts: true
  documents: false

# Important settings (change at own risk)

assets:
  features:
    automatic_img_size: false
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/yarn
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - vendor/
plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
paginate_path: "/posts/page/:num/"
permalink: posts/:slug
